#Soy un comentario
Mkdisk  -path~:~/home/user/Disco2.disk -Unit~:~K -size~:~3000

//Mkdisk -Size~:~3000 –unit~:~K -path~:~/home/user/Disco1.disk

Mkdisk -size~:~4 -unit~:~k -path~:~/home/a/disco.disk #Soy un comentario al final de la linea
pAuSe
mkDisk -size~:~100 -unit~:~m -path~:~/a/discoda.disk
pause #SOY COMENTARIO
rmdisk -path~:~/home/user/Disco2.disk
pause
rmdisk -path~:~/home/a/disco.disk
rmdisk -path~:~/home/user/Disco2.disk